#! /bin/bash
if [ -z "$1" ]; then
	echo "Error, not enough arguments"
	exit 1
elif [ "$1" == "install" ]; then
	python3 -m venv .
    echo "I'm doing setup and pip installs here"
	source ./bin/activate
	pip3 install --upgrade pip
	pip3 install numpy
	pip3 install PyGitHub
	pip3 install Coverage
	pip3 install datetime
	deactivate
	exit 0
elif [ "$1" == "test" ]; then
	echo "Test running"
	python3 -m venv .
	source ./bin/activate
	python3 run.py "$1"
	deactivate
	exit 0
else 
	python3 -m venv .
	source ./bin/activate
	python3 -c 'import ranking_modules; ranking_modules.run("$1")'
	deactivate
	exit 0
fi
